In [120]:
# This code is developed by Pooyan :D

# Hill Cipher
Hill cipher is a polygraphic substitution cipher based on linear algebra.Each letter is represented by a number modulo 26. Often the simple scheme A = 0, B = 1, …, Z = 25 is used, but this is not an essential feature of the cipher. To encrypt a message, each block of n letters (considered as an n-component vector) is multiplied by an invertible n × n matrix, against modulus 26. To decrypt the message, each block is multiplied by the inverse of the matrix used for encryption.
The matrix used for encryption is the cipher key, and it should be chosen randomly from the set of invertible n × n matrices (modulo 26).

In [121]:
import numpy as np
from sympy import Matrix

First define a function to remove all white spaces.

In [122]:
def removeSpaces(text):
    newText = ""
    for i in text:
        if i == " ":
            continue
        else:
            newText = newText + i
    return newText

Here we define the Hill encryption as a function to get a text and return its cipher text.

Now we define the key and its matrix.(it can be any size.)

In [123]:
keySize = 3
temp = [[] for i in range(keySize)]
key = [17, 17, 5, 21, 18, 21, 2, 2, 19]
ind = 0
for i in range(keySize):
    temp[i].append(key[ind:ind+3])
    ind += keySize
arr = np.array(temp)
matrix = np.matrix(arr)
matrix

matrix([[17, 17,  5],
        [21, 18, 21],
        [ 2,  2, 19]])

Now we define a function that take a string with size of key and key then encrypt that.

In [124]:
def encrypt(string, key):
    plain = [''] * len(string)
    for i in range(len(string)):
        plain[i] = ord(string[i]) - ord('a')
    plainMatrix = np.matrix(plain)
    cipher = plainMatrix * key
    for i in cipher:
        i %= 26
        i += ord('A')
    temp = cipher.tolist()
    cipherText = temp[0]
    for i in range(len(cipherText)):
        cipherText[i] = chr(cipherText[i])
    cipher = ''
    for i in cipherText:
        cipher += i
    return cipher
encrypt('sal', matrix)

'QQN'

Here we define a function to encrypt a text completely.

In [125]:
def hillCipher(plainText, key):
    plainText = removeSpaces(plainText)
    while len(plainText) % len(key) != 0:
        plainText += 'x'
    cipher = ''
    size = int(len(plainText) / len(key))
    for i in range(size):
        cipher += encrypt(''.join(plainText[i*3:i*3+3]), key)
    return cipher
hillCipher('salam khubi da', matrix)

'QQNMCAVNGRIZ'

Define a function to calculate modulo matrix inverse.

In [126]:
def matInvMod (matrix, mod):
    width = matrix.shape[0]
    height = matrix.shape[1]
    if width != height:
        raise Exception("No square matrix!")
    tempMatrix = Matrix(matrix)
    matrixInv = tempMatrix.inv_mod(mod)
    inv = np.array(matrixInv)
    k = width
    temp = [[1 for i in range(k)] for j in range(k)]  # just a 2-d list
    tempInv = tempMatrix*matrixInv
    for i in range(k):
        for j in range(k):
            temp[i][j] = tempInv[i,j] % mod
    return inv

Now let's decrypt it.
First we need the inverse matrix of key.

In [127]:
inverse = matInvMod(matrix, 26)
print(inverse)

[[4 9 15]
 [15 17 6]
 [24 0 17]]


Now we define a function that take a string with size of key and key then decrypt that.

In [128]:
def decrypt(string, decryptKey):
    cipher = [''] * len(string)
    for i in range(len(string)):
        cipher[i] = ord(string[i]) - ord('A')
    cipherMatrix = np.matrix(cipher)
    plain = cipherMatrix * decryptKey
    for i in plain:
        i %= 26
        i += ord('a')
    temp = plain.tolist()
    plainText = temp[0]
    for i in range(len(plainText)):
        plainText[i] = chr(int(plainText[i]))
    plain = ''
    for i in plainText:
        plain += i
    return plain
decrypt('QQN', inverse)

'sal'

In [129]:
def hillCipher(cipherText, key):
    while len(cipherText) % len(key) != 0:
        cipherText += 'x'
    plain = ''
    size = int(len(cipherText) / len(key))
    for i in range(size):
        plain += decrypt(''.join(cipherText[i*3:i*3+3]), key)
    return plain
hillCipher('QQNMCAVNGRIZ', inverse)

'salamkhubida'

In [130]:
# Hope you like it ;)