In [32]:
# This code is developed by Pooyan :D

# Hill Attack
As we know the structure of Hill cipher is:
$ \begin{bmatrix} P1 & P2 & P3 \end{bmatrix} \begin{bmatrix} K1 & K2 & K3\\ K4 & K5 & K6\\ K7 & K8 & K9 \end{bmatrix} = \begin{bmatrix} C1 & C2 & C2 \end{bmatrix} $
But if we concat three block of plain text and three block of cipher text we will have:
$ \begin{bmatrix} P1 & P2 & P3\\ P4 & P5 & P6\\ P7 & P8 & P9 \end{bmatrix} \begin{bmatrix} K1 & K2 & K3\\ K4 & K5 & K6\\ K7 & K8 & K9 \end{bmatrix} = \begin{bmatrix} C1 & C2 & C3\\ C4 & C5 & C6\\ C7 & C8 & C9 \end{bmatrix} $
Now for attacking to Hill cipher we can do:
$ P^{-1} \begin{bmatrix} P1 & P2 & P3\\ P4 & P5 & P6\\ P7 & P8 & P9 \end{bmatrix} \begin{bmatrix} K1 & K2 & K3\\ K4 & K5 & K6\\ K7 & K8 & K9 \end{bmatrix} = P^{-1} \begin{bmatrix} C1 & C2 & C3\\ C4 & C5 & C6\\ C7 & C8 & C9 \end{bmatrix} $
$ \begin{bmatrix} K1 & K2 & K3\\ K4 & K5 & K6\\ K7 & K8 & K9 \end{bmatrix} = P^{-1} \begin{bmatrix} C1 & C2 & C3\\ C4 & C5 & C6\\ C7 & C8 & C9 \end{bmatrix} $
So if we find the inverse of P we can attack very easy.

We define a function to read cipher and plain text from files.

In [33]:
def removeSpaces(text):
    newText = ""
    for i in text:
        if i == " ":
            continue
        else:
            newText = newText + i
    return newText


def reader(cipherFileName, plainFileName):
    cipherFile = open(cipherFileName, 'r')
    plainFile = open(plainFileName, 'r')
    cipherText = cipherFile.read()
    plainText = plainFile.read()
    plainText = removeSpaces(plainText)
    return cipherText, plainText


cipher, plain = reader('hillCipher.txt', 'hillPlain.txt')
print(cipher, plain)

SXEFMAIQZIYONEVVJIPWTQNYFPLSSD thisprogramisdevelopedbypooyan


Now working on matrix.

In [36]:
import numpy as np
from sympy import Matrix


def matInvMod (matrix, mod):
    width = matrix.shape[0]
    height = matrix.shape[1]
    if width != height:
        raise Exception("No square matrix!")
    tempMatrix = Matrix(matrix)
    matrixInv = tempMatrix.inv_mod(mod)
    inv = np.array(matrixInv)
    k = width
    temp = [[1 for i in range(k)] for j in range(k)]  # just a 2-d list
    tempInv = tempMatrix*matrixInv
    for i in range(k):
        for j in range(k):
            temp[i][j] = tempInv[i,j] % mod
    return inv


def makeReversibleMatrix(start, end, plainText):
    plainTextTemp = plainText[start:end+1]
    temp = []
    for i in plainTextTemp:
        temp.append(ord(i) - ord('a'))
    keySize = 3
    arr = [[] for i in range(keySize)]
    ind = 0
    for i in range(keySize):
        arr[i].append(temp[ind:ind+3])
        ind += keySize
    arr1 = np.array(arr)
    matrix = np.matrix(arr1)
    return matInvMod(matrix, 26)


print(makeReversibleMatrix(0, 8, plain))

[[25 11 17]
 [12 1 1]
 [18 12 1]]


In [35]:
# Hope you like it ;)