In [50]:
# This code is developed by Pooyan :D

# Hill Cipher
Hill cipher is a polygraphic substitution cipher based on linear algebra.Each letter is represented by a number modulo 26. Often the simple scheme A = 0, B = 1, …, Z = 25 is used, but this is not an essential feature of the cipher. To encrypt a message, each block of n letters (considered as an n-component vector) is multiplied by an invertible n × n matrix, against modulus 26. To decrypt the message, each block is multiplied by the inverse of the matrix used for encryption.
The matrix used for encryption is the cipher key, and it should be chosen randomly from the set of invertible n × n matrices (modulo 26).

Here we define the Hill encryption as a function to get a text and return its cipher text.

In [51]:
import numpy as np

First we define the key and its matrix.(it can be any size.)

In [52]:
keySize = 3
temp = [[] for i in range(keySize)]
key = [17, 17, 5, 21, 18, 21, 2, 2, 19]
ind = 0
for i in range(keySize):
    temp[i].append(key[ind:ind+3])
    ind += keySize
arr = np.array(temp)
matrix = np.matrix(arr)
matrix

matrix([[17, 17,  5],
        [21, 18, 21],
        [ 2,  2, 19]])

Now we define a function that take a string with size of key and key then encrypt that.

In [69]:
def encrypt(string, key):
    plain = [''] * len(string)
    for i in range(len(string)):
        plain[i] = ord(string[i]) - ord('a')
    plainMatrix = np.matrix(plain)
    cipher = plainMatrix * key
    for i in cipher:
        i %= 26
        print(cipher)
        i += ord('A')
    temp = cipher.tolist()
    cipherText = temp[0]
    for i in range(len(cipherText)):
        cipherText[i] = chr(cipherText[i])
    cipher = ''
    for i in cipherText:
        cipher += i
    return cipher
encrypt('poo', matrix)

[[ 5 15 11]]


'FPL'

Here we define a function to encrypt a text completely.

In [71]:
def hillCipher(plainText, key):
    while len(plainText) % len(key) != 0:
        plainText += 'x'
    cipher = ''
    size = int(len(plainText) / len(key))
    for i in range(size):
        cipher += encrypt(''.join(plainText[i*3:i*3+3]), key)
    return cipher
hillCipher('salamkhubida', matrix)

[[16 16 13]]
[[12  2  0]]
[[21 13  6]]
[[17  8 25]]


'QQNMCAVNGRIZ'