In [90]:
# This code is developed by Pooyan :D

# Hill Cipher
Hill cipher is a polygraphic substitution cipher based on linear algebra.Each letter is represented by a number modulo 26. Often the simple scheme A = 0, B = 1, …, Z = 25 is used, but this is not an essential feature of the cipher. To encrypt a message, each block of n letters (considered as an n-component vector) is multiplied by an invertible n × n matrix, against modulus 26. To decrypt the message, each block is multiplied by the inverse of the matrix used for encryption.
The matrix used for encryption is the cipher key, and it should be chosen randomly from the set of invertible n × n matrices (modulo 26).

First define a function to remove all white spaces.

In [91]:
def removeSpaces(text):
    newText = ""
    for i in text:
        if i == " ":
            continue
        else:
            newText = newText + i
    return newText

Here we define the Hill encryption as a function to get a text and return its cipher text.

Now we define the key and its matrix.(it can be any size.)

In [92]:
keySize = 3
temp = [[] for i in range(keySize)]
key = [17, 17, 5, 21, 18, 21, 2, 2, 19]
ind = 0
for i in range(keySize):
    temp[i].append(key[ind:ind+3])
    ind += keySize
arr = np.array(temp)
matrix = np.matrix(arr)
matrix

matrix([[17, 17,  5],
        [21, 18, 21],
        [ 2,  2, 19]])

Now we define a function that take a string with size of key and key then encrypt that.

In [93]:
def encrypt(string, key):
    plain = [''] * len(string)
    for i in range(len(string)):
        plain[i] = ord(string[i]) - ord('a')
    plainMatrix = np.matrix(plain)
    cipher = plainMatrix * key
    for i in cipher:
        i %= 26
        i += ord('A')
    temp = cipher.tolist()
    cipherText = temp[0]
    for i in range(len(cipherText)):
        cipherText[i] = chr(cipherText[i])
    cipher = ''
    for i in cipherText:
        cipher += i
    return cipher
encrypt('sal', matrix)

'QQN'

Here we define a function to encrypt a text completely.

In [94]:
def hillCipher(plainText, key):
    plainText = removeSpaces(plainText)
    while len(plainText) % len(key) != 0:
        plainText += 'x'
    cipher = ''
    size = int(len(plainText) / len(key))
    for i in range(size):
        cipher += encrypt(''.join(plainText[i*3:i*3+3]), key)
    return cipher
hillCipher('salam khubi da', matrix)

'QQNMCAVNGRIZ'

In [95]:
import numpy as np
from sympy import Matrix

def matInvMod (vmnp, mod):
    nr = vmnp.shape[0]
    nc = vmnp.shape[1]
    if (nr!= nc):
        print("Error: Non square matrix! exiting")
        exit()
    vmsym = Matrix(vmnp)
    vmsymInv = vmsym.inv_mod(mod)
    vmnpInv = np.array(vmsymInv)
    print("vmnpInv: ", vmnpInv, "\n")
    k = nr
    vmtest = [[1 for i in range(k)] for j in range(k)]  # just a 2-d list
    vmtestInv = vmsym*vmsymInv
    for i in range(k):
        for j in range(k):
            #print i, j, vmtrx2[i,j] % mod
            vmtest[i][j] = vmtestInv[i,j] % mod
    print("test vmk*vkinv % mod \n:", vmtest)
    return vmnpInv

Now let's decrypt it.
First we need the inverse matrix of key.

In [96]:
inverse = matInvMod(matrix, 26)
print(inverse)

vmnpInv:  [[4 9 15]
 [15 17 6]
 [24 0 17]] 

test vmk*vkinv % mod 
: [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
[[4 9 15]
 [15 17 6]
 [24 0 17]]


Now we define a function that take a string with size of key and key then decrypt that.

In [97]:
def decrypt(string, decryptKey):
    cipher = [''] * len(string)
    for i in range(len(string)):
        cipher[i] = ord(string[i]) - ord('A')
    cipherMatrix = np.matrix(cipher)
    plain = cipherMatrix * decryptKey
    for i in plain:
        i %= 26
        i += ord('a')
    temp = plain.tolist()
    plainText = temp[0]
    for i in range(len(plainText)):
        plainText[i] = chr(int(plainText[i]))
    plain = ''
    for i in plainText:
        plain += i
    return plain
decrypt('QQN', inverse)

'sal'

In [98]:
def hillCipher(cipherText, key):
    while len(cipherText) % len(key) != 0:
        cipherText += 'x'
    plain = ''
    size = int(len(cipherText) / len(key))
    for i in range(size):
        plain += decrypt(''.join(cipherText[i*3:i*3+3]), key)
    return plain
hillCipher('QQNMCAVNGRIZ', inverse)

'salamkhubida'

In [99]:
# Hope you like it ;)